import {$,el,field,option,panel,table,setStatus} from './common/dom.js';import {loadJSON} from './common/data.js';import {downloadJSON,download} from './common/download.js';import {canUseVoice,normalizeRoutine,filterCues,messageSequence,createWhatsAppDraft,exportPlan} from './core.js';import {validAudioFile} from './features/voice.js';
let cues=[],entries=[],audioUrl=null;const app=$('#app');
async function main(){const catalog=await loadJSON('./data/catalog.json');cues=await Promise.all(catalog.items.filter(i=>i.kind==='cue').map(i=>loadJSON('./'+i.path)));const routines=catalog.items.filter(i=>i.kind==='routine');
 const category=el('select',{id:'category'},['all',...new Set(cues.map(c=>c.category))].map(c=>option(c,c)));const cue=el('select',{id:'cue'});function choices(){cue.replaceChildren(...filterCues(cues,category.value).map(c=>option(c.id,c.title)));}category.addEventListener('change',()=>{choices();preview();});choices();cue.addEventListener('change',preview);
 const time=el('input',{id:'cue-time',type:'time',value:'09:00'});const routine=el('select',{id:'routine'},routines.map(i=>option(i.id,i.title)));
 const consent=el('input',{id:'voice-consent',type:'checkbox'});const upload=el('input',{id:'audio-file',type:'file',accept:'audio/*'});const player=el('audio',{id:'audio-preview',controls:true});
 consent.addEventListener('change',()=>{if(!consent.checked){player.pause();player.removeAttribute('src');if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=null;setStatus('Audio permission cleared.');}});
 upload.addEventListener('change',()=>{const file=upload.files[0];if(!consent.checked){setStatus('Confirm permission before audio preview.','error');return;}if(!validAudioFile(file)){setStatus('Choose a supported audio file under 10 MB.','error');return;}if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(file);player.src=audioUrl;setStatus('Local recording ready; no voice clone is created.');});
 const add=el('button',{id:'add-cue',text:'Add to routine',onclick:()=>{try{entries=normalizeRoutine({entries:[...entries,{cue_id:cue.value,time:time.value,day:'daily'}]},cues.map(c=>c.id)).entries;render();setStatus('Cue added to local routine.');}catch(e){setStatus(e.message,'error');}}});
 const load=el('button',{id:'load-routine',class:'secondary',text:'Load example routine',onclick:async()=>{try{const item=routines.find(i=>i.id===routine.value);entries=normalizeRoutine(await loadJSON('./'+item.path),cues.map(c=>c.id)).entries;render();setStatus('Example routine loaded.');}catch(e){setStatus(e.message,'error');}}});
 const sidebar=panel('Routine builder',[field('Cue category',category),field('Care cue',cue),field('Reminder time',time),add,field('Example routine',routine),load]);const content=el('div',{id:'content'});app.append(el('div',{class:'layout'},[el('aside',{},[sidebar,panel('Local audio preview',[field('I have permission to use this recording',consent),field('Select an audio recording',upload),player,el('p',{class:'muted',text:'Preview stays on this device. Voice cloning services are not connected.'})])]),content]));
 window.preview=preview;render();preview();setStatus('30 example care cues available. Nothing is sent.');
 function preview(){const selected=cues.find(c=>c.id===cue.value);if(!selected)return;const node=$('#cue-preview');if(node){node.replaceChildren(el('h3',{text:selected.title}),el('p',{text:selected.text}),el('p',{class:'muted',text:selected.caregiver_note}));}}
}
function render(){const content=$('#content');content.replaceChildren();const messages=messageSequence(entries,cues);const preview=el('div',{id:'cue-preview'});content.append(panel('Cue wording',[preview]),panel('Current routine',[el('div',{class:'scroll'},[table(['Time','Cue'],messages.map(m=>[m.time,m.text]))]),el('div',{class:'actions'},[el('button',{id:'export-json',text:'Export plan JSON',onclick:()=>downloadJSON(exportPlan('SYN-CARE-001',{entries},messages),'smriticare-plan.json')}),el('button',{id:'export-text',class:'secondary',text:'Export WhatsApp text draft',onclick:()=>download(createWhatsAppDraft(messages),'smriticare-draft.txt')}),el('button',{id:'clear-plan',class:'secondary',text:'Clear routine',onclick:()=>{entries=[];render();window.preview();}})])]),panel('Message draft',[el('pre',{id:'message-draft',text:createWhatsAppDraft(messages)||'Add a cue or load an example routine.'})]));if(window.preview)window.preview();}
main().catch(e=>setStatus(e.message,'error'));
